IgnorePath '/.snapshots/*'
IgnorePath '/bin/*'
IgnorePath '/boot/*'
IgnorePath '/dev/*'
IgnorePath '/etc/ca-certificates'
IgnorePath '/etc/fonts'
IgnorePath '/home/*'
IgnorePath '/lib/*'
IgnorePath '/lib64/*'
IgnorePath '/mnt/*'
IgnorePath '/nix/*'
IgnorePath '/opt/*'
IgnorePath '/proc/*'
IgnorePath '/root/*'
IgnorePath '/run/*'
IgnorePath '/run/*'
IgnorePath '/sbin/*'
IgnorePath '/sys/*'
IgnorePath '/tmp/*'
IgnorePath '/usr/*'
IgnorePath '/var/*'

IgnorePath /etc/pacman.d/gnupg/S.gpg-agent
IgnorePath /etc/pacman.d/gnupg/S.gpg-agent.extra
IgnorePath /etc/pacman.d/gnupg/S.gpg-agent.browser
IgnorePath /etc/pacman.d/gnupg/S.gpg-agent.ssh
IgnorePath /etc/ld.so.cache
