IgnorePath '/.snapshots/*'
IgnorePath '/bin/*'
IgnorePath '/boot/*'
IgnorePath '/dev/*'
IgnorePath '/etc/ca-certificates'
IgnorePath '/etc/fonts'
IgnorePath '/home/*'
IgnorePath '/lib/*'
IgnorePath '/lib64/*'
IgnorePath '/mnt/*'
IgnorePath '/nix/*'
IgnorePath '/opt/*'
IgnorePath '/proc/*'
IgnorePath '/root/*'
IgnorePath '/run/*'
IgnorePath '/run/*'
IgnorePath '/sbin/*'
IgnorePath '/sys/*'
IgnorePath '/tmp/*'
IgnorePath '/usr/*'
IgnorePath '/var/*'

IgnorePath /etc/pacman.d/gnupg/S.gpg-agent
IgnorePath /etc/pacman.d/gnupg/S.gpg-agent.extra
IgnorePath /etc/pacman.d/gnupg/S.gpg-agent.browser
IgnorePath /etc/pacman.d/gnupg/S.gpg-agent.ssh
IgnorePath /etc/pacman.d/mirrorlist
IgnorePath /etc/ld.so.cache
IgnorePath /etc/.updated
IgnorePath /etc/pacman.d/mirrorlist
IgnorePath /etc/pacman.d/gnupg/openpgp-revocs.d
IgnorePath /etc/pacman.d/gnupg/private-keys-v1.d
IgnorePath /etc/pacman.d/gnupg/*.gpg*
IgnorePath /etc/pacman.d/gnupg/tofu.db
IgnorePath /etc/refind.d/keys
IgnorePath /etc/resolv.conf
IgnorePath /etc/ssh
IgnorePath /etc/ssl/certs
IgnorePath /etc/dconf/db/ibus
