IgnorePath '/.snapshots/*'
IgnorePath '/bin/*'
IgnorePath '/boot/*'
IgnorePath '/dev/*'
IgnorePath '/etc/ca-certificates'
IgnorePath '/etc/fonts'
IgnorePath '/home/*'
IgnorePath '/lib/*'
IgnorePath '/lib64/*'
IgnorePath '/mnt/*'
IgnorePath '/nix/*'
IgnorePath '/opt/*'
IgnorePath '/proc/*'
IgnorePath '/root/*'
IgnorePath '/run/*'
IgnorePath '/run/*'
IgnorePath '/sbin/*'
IgnorePath '/sys/*'
IgnorePath '/tmp/*'
IgnorePath '/usr/*'
IgnorePath '/var/*'

IgnorePath /etc/*.lock
IgnorePath /etc/.updated
IgnorePath /etc/adjtime
IgnorePath /etc/group-
IgnorePath /etc/gshadow
IgnorePath /etc/gshadow-
IgnorePath /etc/ld.so.cache
IgnorePath /etc/passwd*
IgnorePath /etc/shadow*
IgnorePath /etc/ssh
IgnorePath /etc/ssl
IgnorePath /etc/subgid*
IgnorePath /etc/subuid*
